version: '3.9'

services:
  training:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/
    networks:
      - my_network
    command: tail -f /dev/null
    environment:
      - PYTHONPATH=/app

networks:
  my_network:
