version: '3.9'

services:
  youtube_api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app

    command: tail -f /dev/null
    environment:
      - PYTHONPATH=/app
